name: Auto-Update README

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Generate README
        run: node generate-readme.js

      - name: Fetch latest from remote
        run: |
          git fetch origin
          git reset --hard origin/master

      - name: Commit and push README
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: auto-update README"
          git pull --rebase origin master  # Pull remote changes first
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/machage9603/readmeaker.git --force  # Force push to avoid conflicts
