name: Auto-Update README

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

permissions:
  contents: write #grant bot permission to commit and push changes


jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Ensure we are in the root directory (default, but being explicit)
      - name: Set up working directory
        run: cd ${{ github.workspace }}

      # Install necessary dependencies (if needed for your project)
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run the generate-readme.js script (located in the root)
      - name: Generate README
        run: node generate-readme.js

      # Commit and push updated README
      - name: Push changes
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: auto-update README"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/machage9603/readmeaker.git

