name: Auto-Update README

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Ensure we are in the root directory (default, but being explicit)
      - name: Set up working directory
        run: cd ${{ github.workspace }}

      # Install necessary dependencies (if needed for your project)
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run the generate-readme.js script (located in the root)
      - name: Generate README
        run: node generate-readme.js

      # Commit and push updated README
      - name: Commit and push README
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: auto-update README"
          git push
